In [11]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
import pandas as pd
df = pd.read_csv('drive/My Drive/datasets/salary_data.csv')
df=df.round(decimals=1)
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [31]:

import numpy as np

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import matplotlib.pyplot as plt


class LinRegression() :
	
	def __init__( self, learning_rate, iterations ) :
		
		self.learning_rate = learning_rate
		
		self.iterations = iterations
		
			
	def fit( self, X, Y ) :
		
		
		self.m, self.n = X.shape
		
		# weight initialization
		
		self.W = np.zeros( self.n )
		
		self.b = 0
		
		self.X = X
		
		self.Y = Y
		
		
		# gradient descent learning
				
		for i in range( self.iterations ) :
			
			self.update_weights()
			
		return self
	
	# Helper function to update weights in gradient descent
	
	def update_weights( self ) :
			
		Y_pred = self.predict( self.X )
		
		# calculate gradients
	
		dW = - ( 2 * ( self.X.T ).dot( self.Y - Y_pred ) ) / self.m
	
		db = - 2 * np.sum( self.Y - Y_pred ) / self.m
		
		# update weights
	
		self.W = self.W - self.learning_rate * dW
	
		self.b = self.b - self.learning_rate * db
		
		return self
	
	# Hypothetical function h( x )
	
	def predict( self, X ) :
	
		return X.dot( self.W ) + self.b
	


def main() :
	
	
	df=df = pd.read_csv('drive/My Drive/datasets/salary_data.csv')

	X = df.iloc[:,:-1].values

	Y = df.iloc[:,1].values
	

	X_train, X_test, Y_train, Y_test = train_test_split(
	X, Y, test_size = 1/3, random_state = 0 )
	
	
	model = LinRegression( learning_rate = 0.01, iterations = 100 )
	model.fit( X_train, Y_train )
	model1 = LinearRegression()
	model1.fit( X_train, Y_train)
	# Prediction on test set
	Y_pred = model.predict( X_test )
	Y_pred1 = model1.predict( X_test )
	
	print( "Predicted values ", np.round( Y_pred[:3], 2 ) )
	
	print( "Real values	 ", Y_test[:3] )
	
	print( "Trained W	 ", round( model.W[0], 2 ) )
	
	print( "Trained b	 ", round( model.b, 2 ) )
	


if __name__ == "__main__" :
	
	main()

Predicted values  [ 28861.74 134323.88  60021.01]
Real values	  [ 37731. 122391.  57081.]
Trained W	  11984.33
Trained b	  10885.24